import type { Team } from "./types";

export const teams: Team[] = [
  {
    id: "mygo",
    name: "mygo",
    tag: "MYG",
    enName: "MYGO",
    status: "LIVE TRACKING",
    totalScore: "8275.7",
    rank: 1,
    manifesto: "以稳定推进为第一优先，四人轮转配合，确保每局都打出完整执行。",
    radarStats: [
      { label: "执行力", value: 91 },
      { label: "策略性", value: 86 },
      { label: "抗压性", value: 89 },
      { label: "经济运营", value: 84 },
      { label: "熟练度", value: 90 },
      { label: "终局收束", value: 88 },
    ],
    members: [
      {
        id: "P1",
        name: "吃豆腐蘸酱",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/mygo/吃豆腐蘸酱.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "红白白",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/mygo/红白白.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "若亭",
        role: "运营位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/mygo/若亭.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "雪月花",
        role: "终局位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/mygo/雪月花.jpg",
        operatorPicks: [],
      },
    ],
  },
  {
    id: "tianqi-siqushi",
    name: "天启四区士",
    tag: "TQS",
    enName: "APOCALYPSE QUARTET",
    status: "READY",
    totalScore: "9595.3",
    rank: 2,
    manifesto: "稳中求快，尽量把每一次希望和源石锭消耗都换成稳定分数。",
    radarStats: [
      { label: "执行力", value: 88 },
      { label: "策略性", value: 85 },
      { label: "抗压性", value: 87 },
      { label: "经济运营", value: 83 },
      { label: "熟练度", value: 86 },
      { label: "终局收束", value: 85 },
    ],
    members: [
      {
        id: "P1",
        name: "某大叔速水好",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/天启四区士/某大叔速水好.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "拾壹月的鹤主",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/天启四区士/拾壹月的鹤主.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "忍野忍不下去",
        role: "运营位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/天启四区士/忍野忍不下去.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "起步之志",
        role: "终局位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/天启四区士/起步之志.jpg",
        operatorPicks: [],
      },
    ],
  },
  {
    id: "siqu-brothers",
    name: "四驱兄弟想队名",
    tag: "SQX",
    enName: "4WD BROS",
    status: "READY",
    totalScore: "5040.9",
    rank: 3,
    manifesto: "速度与细节并重，确保每一棒都能平稳接力。",
    radarStats: [
      { label: "执行力", value: 86 },
      { label: "策略性", value: 83 },
      { label: "抗压性", value: 84 },
      { label: "经济运营", value: 82 },
      { label: "熟练度", value: 88 },
      { label: "终局收束", value: 84 },
    ],
    members: [
      {
        id: "P1",
        name: "朝霞",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/四驱兄弟想队名/朝霞.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "Aimer",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/四驱兄弟想队名/Aimer.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "洛齐克",
        role: "运营位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/四驱兄弟想队名/洛齐克.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "顾秦",
        role: "终局位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/四驱兄弟想队名/顾秦.jpg",
        operatorPicks: [],
      },
    ],
  },
  {
    id: "strawberry-no1",
    name: "草莓天下第一",
    tag: "CMY",
    enName: "STRAWBERRY NO.1",
    status: "READY",
    totalScore: "12692.0",
    rank: 4,
    manifesto: "保持稳定节奏，先拿到确定分，再冲击紧急作战高收益路线。",
    radarStats: [
      { label: "执行力", value: 85 },
      { label: "策略性", value: 84 },
      { label: "抗压性", value: 86 },
      { label: "经济运营", value: 85 },
      { label: "熟练度", value: 83 },
      { label: "终局收束", value: 82 },
    ],
    members: [
      {
        id: "P1",
        name: "浪淘沙尽天涯",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/草莓天下第一/浪淘沙尽天涯.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "言",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/草莓天下第一/言.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "糖该葡萄糖",
        role: "运营位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/草莓天下第一/糖该葡萄糖.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "归零",
        role: "终局位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/草莓天下第一/归零.jpg",
        operatorPicks: [],
      },
    ],
  },
  {
    id: "feirenzai",
    name: "非人哉",
    tag: "FRZ",
    enName: "FEI REN ZAI",
    status: "READY",
    totalScore: "9186.7",
    rank: 5,
    manifesto: "打法灵活但不失稳健，核心目标是每棒都打出分数下限保障。",
    radarStats: [
      { label: "执行力", value: 84 },
      { label: "策略性", value: 82 },
      { label: "抗压性", value: 88 },
      { label: "经济运营", value: 80 },
      { label: "熟练度", value: 85 },
      { label: "终局收束", value: 84 },
    ],
    members: [
      {
        id: "P1",
        name: "last要楽奈丶",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/非人哉/last要楽奈丶.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "呃呃啊啊",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/非人哉/呃呃啊啊.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "海嗣",
        role: "运营位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/非人哉/海嗣.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "圣人又土",
        role: "终局位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/非人哉/圣人又土.jpg",
        operatorPicks: [],
      },
    ],
  },
  {
    id: "feixing-xuerong",
    name: "飞行雪绒",
    tag: "FXR",
    enName: "FLYING SNOW VELVET",
    status: "READY",
    totalScore: "7862.0",
    rank: 6,
    manifesto: "以精确运营为主轴，确保关键节点的容错和藏品收益最大化。",
    radarStats: [
      { label: "执行力", value: 83 },
      { label: "策略性", value: 87 },
      { label: "抗压性", value: 82 },
      { label: "经济运营", value: 86 },
      { label: "熟练度", value: 84 },
      { label: "终局收束", value: 83 },
    ],
    members: [
      {
        id: "P1",
        name: "幻尘",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/飞行雪绒/幻尘.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "快晴",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/飞行雪绒/快晴.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "魔法蜘蛛",
        role: "运营位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/飞行雪绒/魔法蜘蛛.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "白身鱼",
        role: "终局位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/飞行雪绒/白身鱼.jpg",
        operatorPicks: [],
      },
    ],
  },
  {
    id: "mofa-strategy",
    name: "魔法战略的集成审判",
    tag: "MFS",
    enName: "ARCANE STRATEGY TRIBUNAL",
    status: "READY",
    totalScore: "6122.4",
    rank: 7,
    manifesto: "以全局规划为先，强调路线决策、希望分配和终局收束协同。",
    radarStats: [
      { label: "执行力", value: 82 },
      { label: "策略性", value: 90 },
      { label: "抗压性", value: 84 },
      { label: "经济运营", value: 89 },
      { label: "熟练度", value: 82 },
      { label: "终局收束", value: 86 },
    ],
    members: [
      {
        id: "P1",
        name: "兔头无权为我授勋",
        role: "开局位",
        theme: "探索者的银凇止境",
        signatureOp: "待补充",
        squad: "主攻分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/魔法战略的集成审判/兔头无权为我授勋.jpg",
        operatorPicks: [],
      },
      {
        id: "P2",
        name: "酱香企鹅",
        role: "推进位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "推进分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/魔法战略的集成审判/酱香企鹅.jpg",
        operatorPicks: [],
      },
      {
        id: "P3",
        name: "淮南牛肉汤",
        role: "运营位",
        theme: "萨卡兹的无终奇语",
        signatureOp: "待补充",
        squad: "运营分队",
        note: "选手资料已同步，详细战术信息待补充。",
        avatar: "/contestants/魔法战略的集成审判/淮南牛肉汤.jpg",
        operatorPicks: [],
      },
      {
        id: "P4",
        name: "布兰卡",
        role: "终局位",
        theme: "岁的界园志异",
        signatureOp: "待补充",
        squad: "终局分队",
        note: "🚨 该选手担任本队抗压位。",
        avatar: "/contestants/魔法战略的集成审判/布兰卡.jpg",
        operatorPicks: [],
      },
    ],
  },
];
